name: Test and build

on:
  pull_request:
  push:

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Build modules
        run: mvn -B package --file pom.xml -DskipTests

      - name: List all jars (debug)
        run: find . -name "*.jar"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: '**/target/*.jar'
          if-no-files-found: error
